/** WARNING! This file is auto-generated. Please do not edit! */
import { useAcceptedCurrencies, AcceptedCurrenciesArguments, AcceptedCurrenciesOptions } from './modules/use-accepted-currencies';
export * from './modules/use-accepted-currencies';
import { useAddAcceptedCurrency, AddAcceptedCurrencyArguments, AddAcceptedCurrencyOptions } from './modules/use-add-accepted-currency';
export * from './modules/use-add-accepted-currency';
import { useAddAdmin, AddAdminArguments, AddAdminOptions } from './modules/use-add-admin';
export * from './modules/use-add-admin';
import { useAddCollection, AddCollectionArguments, AddCollectionOptions } from './modules/use-add-collection';
export * from './modules/use-add-collection';
import { useAddFactory, AddFactoryArguments, AddFactoryOptions } from './modules/use-add-factory';
export * from './modules/use-add-factory';
import { useAdminList, AdminListArguments, AdminListOptions } from './modules/use-admin-list';
export * from './modules/use-admin-list';
import { useAdmins, AdminsArguments, AdminsOptions } from './modules/use-admins';
export * from './modules/use-admins';
import { useBlackListCollection, BlackListCollectionArguments, BlackListCollectionOptions } from './modules/use-black-list-collection';
export * from './modules/use-black-list-collection';
import { useChainId, ChainIdOptions } from './modules/use-chain-id';
export * from './modules/use-chain-id';
import { useClaimDepositAndRemoveCollection, ClaimDepositAndRemoveCollectionArguments, ClaimDepositAndRemoveCollectionOptions } from './modules/use-claim-deposit-and-remove-collection';
export * from './modules/use-claim-deposit-and-remove-collection';
import { useCollectionVerificationFee, CollectionVerificationFeeOptions } from './modules/use-collection-verification-fee';
export * from './modules/use-collection-verification-fee';
import { useDeclineVerification, DeclineVerificationArguments, DeclineVerificationOptions } from './modules/use-decline-verification';
export * from './modules/use-decline-verification';
import { useFactories, FactoriesArguments, FactoriesOptions } from './modules/use-factories';
export * from './modules/use-factories';
import { useFactoryList, FactoryListArguments, FactoryListOptions } from './modules/use-factory-list';
export * from './modules/use-factory-list';
import { useGetCollectionAddressByIndex, GetCollectionAddressByIndexArguments, GetCollectionAddressByIndexOptions } from './modules/use-get-collection-address-by-index';
export * from './modules/use-get-collection-address-by-index';
import { useGetCollectionByAddress, GetCollectionByAddressArguments, GetCollectionByAddressOptions } from './modules/use-get-collection-by-address';
export * from './modules/use-get-collection-by-address';
import { useGetCollectionByIndex, GetCollectionByIndexArguments, GetCollectionByIndexOptions } from './modules/use-get-collection-by-index';
export * from './modules/use-get-collection-by-index';
import { useGetCollectionVerificationFee, GetCollectionVerificationFeeOptions } from './modules/use-get-collection-verification-fee';
export * from './modules/use-get-collection-verification-fee';
import { useGetRmrkTokenAddress, GetRmrkTokenAddressOptions } from './modules/use-get-rmrk-token-address';
export * from './modules/use-get-rmrk-token-address';
import { useGetTotalCollectionCount, GetTotalCollectionCountOptions } from './modules/use-get-total-collection-count';
export * from './modules/use-get-total-collection-count';
import { useOwner, OwnerOptions } from './modules/use-owner';
export * from './modules/use-owner';
import { useRemoveAcceptedCurrency, RemoveAcceptedCurrencyArguments, RemoveAcceptedCurrencyOptions } from './modules/use-remove-accepted-currency';
export * from './modules/use-remove-accepted-currency';
import { useRemoveAdmin, RemoveAdminArguments, RemoveAdminOptions } from './modules/use-remove-admin';
export * from './modules/use-remove-admin';
import { useRemoveFactory, RemoveFactoryArguments, RemoveFactoryOptions } from './modules/use-remove-factory';
export * from './modules/use-remove-factory';
import { useRenounceOwnership, RenounceOwnershipOptions } from './modules/use-renounce-ownership';
export * from './modules/use-renounce-ownership';
import { useRmrkToken, RmrkTokenOptions } from './modules/use-rmrk-token';
export * from './modules/use-rmrk-token';
import { useSponsorVerification, SponsorVerificationArguments, SponsorVerificationOptions } from './modules/use-sponsor-verification';
export * from './modules/use-sponsor-verification';
import { useTotalCollectionsCounter, TotalCollectionsCounterOptions } from './modules/use-total-collections-counter';
export * from './modules/use-total-collections-counter';
import { useTransferOwnership, TransferOwnershipArguments, TransferOwnershipOptions } from './modules/use-transfer-ownership';
export * from './modules/use-transfer-ownership';
import { useUnblackListCollection, UnblackListCollectionArguments, UnblackListCollectionOptions } from './modules/use-unblack-list-collection';
export * from './modules/use-unblack-list-collection';
import { useUpdateCollectionVerificationFee, UpdateCollectionVerificationFeeArguments, UpdateCollectionVerificationFeeOptions } from './modules/use-update-collection-verification-fee';
export * from './modules/use-update-collection-verification-fee';
import { useVerifyCollection, VerifyCollectionArguments, VerifyCollectionOptions } from './modules/use-verify-collection';
export * from './modules/use-verify-collection';
import { useWithdrawFees, WithdrawFeesOptions } from './modules/use-withdraw-fees';
export * from './modules/use-withdraw-fees';
export declare const RMRKRegistry: {
    useAcceptedCurrencies(args: AcceptedCurrenciesArguments[], opts: AcceptedCurrenciesOptions): ReturnType<typeof useAcceptedCurrencies>;
    useAddAcceptedCurrency(args: AddAcceptedCurrencyArguments, opts: AddAcceptedCurrencyOptions): ReturnType<typeof useAddAcceptedCurrency>;
    useAddAdmin(args: AddAdminArguments, opts: AddAdminOptions): ReturnType<typeof useAddAdmin>;
    useAddCollection(args: AddCollectionArguments, opts: AddCollectionOptions): ReturnType<typeof useAddCollection>;
    useAddFactory(args: AddFactoryArguments, opts: AddFactoryOptions): ReturnType<typeof useAddFactory>;
    useAdminList(args: AdminListArguments[], opts: AdminListOptions): ReturnType<typeof useAdminList>;
    useAdmins(args: AdminsArguments[], opts: AdminsOptions): ReturnType<typeof useAdmins>;
    useBlackListCollection(args: BlackListCollectionArguments, opts: BlackListCollectionOptions): ReturnType<typeof useBlackListCollection>;
    useChainId(opts: ChainIdOptions): ReturnType<typeof useChainId>;
    useClaimDepositAndRemoveCollection(args: ClaimDepositAndRemoveCollectionArguments, opts: ClaimDepositAndRemoveCollectionOptions): ReturnType<typeof useClaimDepositAndRemoveCollection>;
    useCollectionVerificationFee(opts: CollectionVerificationFeeOptions): ReturnType<typeof useCollectionVerificationFee>;
    useDeclineVerification(args: DeclineVerificationArguments, opts: DeclineVerificationOptions): ReturnType<typeof useDeclineVerification>;
    useFactories(args: FactoriesArguments[], opts: FactoriesOptions): ReturnType<typeof useFactories>;
    useFactoryList(args: FactoryListArguments[], opts: FactoryListOptions): ReturnType<typeof useFactoryList>;
    useGetCollectionAddressByIndex(args: GetCollectionAddressByIndexArguments[], opts: GetCollectionAddressByIndexOptions): ReturnType<typeof useGetCollectionAddressByIndex>;
    useGetCollectionByAddress(args: GetCollectionByAddressArguments[], opts: GetCollectionByAddressOptions): ReturnType<typeof useGetCollectionByAddress>;
    useGetCollectionByIndex(args: GetCollectionByIndexArguments[], opts: GetCollectionByIndexOptions): ReturnType<typeof useGetCollectionByIndex>;
    useGetCollectionVerificationFee(opts: GetCollectionVerificationFeeOptions): ReturnType<typeof useGetCollectionVerificationFee>;
    useGetRmrkTokenAddress(opts: GetRmrkTokenAddressOptions): ReturnType<typeof useGetRmrkTokenAddress>;
    useGetTotalCollectionCount(opts: GetTotalCollectionCountOptions): ReturnType<typeof useGetTotalCollectionCount>;
    useOwner(opts: OwnerOptions): ReturnType<typeof useOwner>;
    useRemoveAcceptedCurrency(args: RemoveAcceptedCurrencyArguments, opts: RemoveAcceptedCurrencyOptions): ReturnType<typeof useRemoveAcceptedCurrency>;
    useRemoveAdmin(args: RemoveAdminArguments, opts: RemoveAdminOptions): ReturnType<typeof useRemoveAdmin>;
    useRemoveFactory(args: RemoveFactoryArguments, opts: RemoveFactoryOptions): ReturnType<typeof useRemoveFactory>;
    useRenounceOwnership(opts: RenounceOwnershipOptions): ReturnType<typeof useRenounceOwnership>;
    useRmrkToken(opts: RmrkTokenOptions): ReturnType<typeof useRmrkToken>;
    useSponsorVerification(args: SponsorVerificationArguments, opts: SponsorVerificationOptions): ReturnType<typeof useSponsorVerification>;
    useTotalCollectionsCounter(opts: TotalCollectionsCounterOptions): ReturnType<typeof useTotalCollectionsCounter>;
    useTransferOwnership(args: TransferOwnershipArguments, opts: TransferOwnershipOptions): ReturnType<typeof useTransferOwnership>;
    useUnblackListCollection(args: UnblackListCollectionArguments, opts: UnblackListCollectionOptions): ReturnType<typeof useUnblackListCollection>;
    useUpdateCollectionVerificationFee(args: UpdateCollectionVerificationFeeArguments, opts: UpdateCollectionVerificationFeeOptions): ReturnType<typeof useUpdateCollectionVerificationFee>;
    useVerifyCollection(args: VerifyCollectionArguments, opts: VerifyCollectionOptions): ReturnType<typeof useVerifyCollection>;
    useWithdrawFees(opts: WithdrawFeesOptions): ReturnType<typeof useWithdrawFees>;
};
