/** WARNING! This file is auto-generated. Please do not edit! */
import { useVERSION, VERSIONOptions } from './modules/use-version';
export * from './modules/use-version';
import { useAcceptAsset, AcceptAssetArguments, AcceptAssetOptions } from './modules/use-accept-asset';
export * from './modules/use-accept-asset';
import { useAcceptChild, AcceptChildArguments, AcceptChildOptions } from './modules/use-accept-child';
export * from './modules/use-accept-child';
import { AddAssetEntryArguments, AddAssetEntryOptions, UseRMRKEquippableImplAddAssetEntryReturnValue } from './modules/use-add-asset-entry';
export * from './modules/use-add-asset-entry';
import { useAddAssetToToken, AddAssetToTokenArguments, AddAssetToTokenOptions } from './modules/use-add-asset-to-token';
export * from './modules/use-add-asset-to-token';
import { useAddChild, AddChildArguments, AddChildOptions } from './modules/use-add-child';
export * from './modules/use-add-child';
import { AddEquippableAssetEntryArguments, AddEquippableAssetEntryOptions, UseRMRKEquippableImplAddEquippableAssetEntryReturnValue } from './modules/use-add-equippable-asset-entry';
export * from './modules/use-add-equippable-asset-entry';
import { useApprove, ApproveArguments, ApproveOptions } from './modules/use-approve';
export * from './modules/use-approve';
import { useApproveForAssets, ApproveForAssetsArguments, ApproveForAssetsOptions } from './modules/use-approve-for-assets';
export * from './modules/use-approve-for-assets';
import { useBalanceOf, BalanceOfArguments, BalanceOfOptions } from './modules/use-balance-of';
export * from './modules/use-balance-of';
import { useBurn, BurnArguments, BurnOptions } from './modules/use-burn';
export * from './modules/use-burn';
import { useCanTokenBeEquippedWithAssetIntoSlot, CanTokenBeEquippedWithAssetIntoSlotArguments, CanTokenBeEquippedWithAssetIntoSlotOptions } from './modules/use-can-token-be-equipped-with-asset-into-slot';
export * from './modules/use-can-token-be-equipped-with-asset-into-slot';
import { useChildIsInActive, ChildIsInActiveArguments, ChildIsInActiveOptions } from './modules/use-child-is-in-active';
export * from './modules/use-child-is-in-active';
import { useChildOf, ChildOfArguments, ChildOfOptions } from './modules/use-child-of';
export * from './modules/use-child-of';
import { useChildrenOf, ChildrenOfArguments, ChildrenOfOptions } from './modules/use-children-of';
export * from './modules/use-children-of';
import { useCollectionMetadata, CollectionMetadataOptions } from './modules/use-collection-metadata';
export * from './modules/use-collection-metadata';
import { useDirectOwnerOf, DirectOwnerOfArguments, DirectOwnerOfOptions } from './modules/use-direct-owner-of';
export * from './modules/use-direct-owner-of';
import { useEquip, EquipArguments, EquipOptions } from './modules/use-equip';
export * from './modules/use-equip';
import { useGetActiveAssetPriorities, GetActiveAssetPrioritiesArguments, GetActiveAssetPrioritiesOptions } from './modules/use-get-active-asset-priorities';
export * from './modules/use-get-active-asset-priorities';
import { useGetActiveAssets, GetActiveAssetsArguments, GetActiveAssetsOptions } from './modules/use-get-active-assets';
export * from './modules/use-get-active-assets';
import { useGetApproved, GetApprovedArguments, GetApprovedOptions } from './modules/use-get-approved';
export * from './modules/use-get-approved';
import { useGetApprovedForAssets, GetApprovedForAssetsArguments, GetApprovedForAssetsOptions } from './modules/use-get-approved-for-assets';
export * from './modules/use-get-approved-for-assets';
import { useGetAssetAndEquippableData, GetAssetAndEquippableDataArguments, GetAssetAndEquippableDataOptions } from './modules/use-get-asset-and-equippable-data';
export * from './modules/use-get-asset-and-equippable-data';
import { useGetAssetMetadata, GetAssetMetadataArguments, GetAssetMetadataOptions } from './modules/use-get-asset-metadata';
export * from './modules/use-get-asset-metadata';
import { useGetAssetReplacements, GetAssetReplacementsArguments, GetAssetReplacementsOptions } from './modules/use-get-asset-replacements';
export * from './modules/use-get-asset-replacements';
import { useGetEquipment, GetEquipmentArguments, GetEquipmentOptions } from './modules/use-get-equipment';
export * from './modules/use-get-equipment';
import { useGetLock, GetLockOptions } from './modules/use-get-lock';
export * from './modules/use-get-lock';
import { useGetPendingAssets, GetPendingAssetsArguments, GetPendingAssetsOptions } from './modules/use-get-pending-assets';
export * from './modules/use-get-pending-assets';
import { useGetRoyaltyPercentage, GetRoyaltyPercentageOptions } from './modules/use-get-royalty-percentage';
export * from './modules/use-get-royalty-percentage';
import { useGetRoyaltyRecipient, GetRoyaltyRecipientOptions } from './modules/use-get-royalty-recipient';
export * from './modules/use-get-royalty-recipient';
import { useIsApprovedForAll, IsApprovedForAllArguments, IsApprovedForAllOptions } from './modules/use-is-approved-for-all';
export * from './modules/use-is-approved-for-all';
import { useIsApprovedForAllForAssets, IsApprovedForAllForAssetsArguments, IsApprovedForAllForAssetsOptions } from './modules/use-is-approved-for-all-for-assets';
export * from './modules/use-is-approved-for-all-for-assets';
import { useIsChildEquipped, IsChildEquippedArguments, IsChildEquippedOptions } from './modules/use-is-child-equipped';
export * from './modules/use-is-child-equipped';
import { useIsContributor, IsContributorArguments, IsContributorOptions } from './modules/use-is-contributor';
export * from './modules/use-is-contributor';
import { useManageContributor, ManageContributorArguments, ManageContributorOptions } from './modules/use-manage-contributor';
export * from './modules/use-manage-contributor';
import { useMaxSupply, MaxSupplyOptions } from './modules/use-max-supply';
export * from './modules/use-max-supply';
import { useMint, MintArguments, MintOptions } from './modules/use-mint';
export * from './modules/use-mint';
import { useName, NameOptions } from './modules/use-name';
export * from './modules/use-name';
import { useNestMint, NestMintArguments, NestMintOptions } from './modules/use-nest-mint';
export * from './modules/use-nest-mint';
import { useNestTransferFrom, NestTransferFromArguments, NestTransferFromOptions } from './modules/use-nest-transfer-from';
export * from './modules/use-nest-transfer-from';
import { useOwner, OwnerOptions } from './modules/use-owner';
export * from './modules/use-owner';
import { useOwnerOf, OwnerOfArguments, OwnerOfOptions } from './modules/use-owner-of';
export * from './modules/use-owner-of';
import { usePendingChildOf, PendingChildOfArguments, PendingChildOfOptions } from './modules/use-pending-child-of';
export * from './modules/use-pending-child-of';
import { usePendingChildrenOf, PendingChildrenOfArguments, PendingChildrenOfOptions } from './modules/use-pending-children-of';
export * from './modules/use-pending-children-of';
import { usePricePerMint, PricePerMintOptions } from './modules/use-price-per-mint';
export * from './modules/use-price-per-mint';
import { useRejectAllAssets, RejectAllAssetsArguments, RejectAllAssetsOptions } from './modules/use-reject-all-assets';
export * from './modules/use-reject-all-assets';
import { useRejectAllChildren, RejectAllChildrenArguments, RejectAllChildrenOptions } from './modules/use-reject-all-children';
export * from './modules/use-reject-all-children';
import { useRejectAsset, RejectAssetArguments, RejectAssetOptions } from './modules/use-reject-asset';
export * from './modules/use-reject-asset';
import { useRenounceOwnership, RenounceOwnershipOptions } from './modules/use-renounce-ownership';
export * from './modules/use-renounce-ownership';
import { useRoyaltyInfo, RoyaltyInfoArguments, RoyaltyInfoOptions } from './modules/use-royalty-info';
export * from './modules/use-royalty-info';
import { useSafeTransferFrom, SafeTransferFromArguments, SafeTransferFromOptions } from './modules/use-safe-transfer-from';
export * from './modules/use-safe-transfer-from';
import { useSetApprovalForAll, SetApprovalForAllArguments, SetApprovalForAllOptions } from './modules/use-set-approval-for-all';
export * from './modules/use-set-approval-for-all';
import { useSetApprovalForAllForAssets, SetApprovalForAllForAssetsArguments, SetApprovalForAllForAssetsOptions } from './modules/use-set-approval-for-all-for-assets';
export * from './modules/use-set-approval-for-all-for-assets';
import { useSetLock, SetLockOptions } from './modules/use-set-lock';
export * from './modules/use-set-lock';
import { useSetPriority, SetPriorityArguments, SetPriorityOptions } from './modules/use-set-priority';
export * from './modules/use-set-priority';
import { useSetValidParentForEquippableGroup, SetValidParentForEquippableGroupArguments, SetValidParentForEquippableGroupOptions } from './modules/use-set-valid-parent-for-equippable-group';
export * from './modules/use-set-valid-parent-for-equippable-group';
import { useSupportsInterface, SupportsInterfaceArguments, SupportsInterfaceOptions } from './modules/use-supports-interface';
export * from './modules/use-supports-interface';
import { useSymbol, SymbolOptions } from './modules/use-symbol';
export * from './modules/use-symbol';
import { useTokenURI, TokenURIArguments, TokenURIOptions } from './modules/use-token-uri';
export * from './modules/use-token-uri';
import { useTotalAssets, TotalAssetsOptions } from './modules/use-total-assets';
export * from './modules/use-total-assets';
import { useTotalSupply, TotalSupplyOptions } from './modules/use-total-supply';
export * from './modules/use-total-supply';
import { useTransferChild, TransferChildArguments, TransferChildOptions } from './modules/use-transfer-child';
export * from './modules/use-transfer-child';
import { useTransferFrom, TransferFromArguments, TransferFromOptions } from './modules/use-transfer-from';
export * from './modules/use-transfer-from';
import { useTransferOwnership, TransferOwnershipArguments, TransferOwnershipOptions } from './modules/use-transfer-ownership';
export * from './modules/use-transfer-ownership';
import { useUnequip, UnequipArguments, UnequipOptions } from './modules/use-unequip';
export * from './modules/use-unequip';
import { useUpdateRoyaltyRecipient, UpdateRoyaltyRecipientArguments, UpdateRoyaltyRecipientOptions } from './modules/use-update-royalty-recipient';
export * from './modules/use-update-royalty-recipient';
import { useWithdrawRaised, WithdrawRaisedArguments, WithdrawRaisedOptions } from './modules/use-withdraw-raised';
export * from './modules/use-withdraw-raised';
export declare const RMRKEquippable: {
    useVERSION(opts: VERSIONOptions): ReturnType<typeof useVERSION>;
    useAcceptAsset(args: AcceptAssetArguments, opts: AcceptAssetOptions): ReturnType<typeof useAcceptAsset>;
    useAcceptChild(args: AcceptChildArguments, opts: AcceptChildOptions): ReturnType<typeof useAcceptChild>;
    useAddAssetEntry(args: AddAssetEntryArguments, opts: AddAssetEntryOptions): UseRMRKEquippableImplAddAssetEntryReturnValue;
    useAddAssetToToken(args: AddAssetToTokenArguments, opts: AddAssetToTokenOptions): ReturnType<typeof useAddAssetToToken>;
    useAddChild(args: AddChildArguments, opts: AddChildOptions): ReturnType<typeof useAddChild>;
    useAddEquippableAssetEntry(args: AddEquippableAssetEntryArguments, opts: AddEquippableAssetEntryOptions): UseRMRKEquippableImplAddEquippableAssetEntryReturnValue;
    useApprove(args: ApproveArguments, opts: ApproveOptions): ReturnType<typeof useApprove>;
    useApproveForAssets(args: ApproveForAssetsArguments, opts: ApproveForAssetsOptions): ReturnType<typeof useApproveForAssets>;
    useBalanceOf(args: BalanceOfArguments[], opts: BalanceOfOptions): ReturnType<typeof useBalanceOf>;
    useBurn(args: BurnArguments, opts: BurnOptions): ReturnType<typeof useBurn>;
    useCanTokenBeEquippedWithAssetIntoSlot(args: CanTokenBeEquippedWithAssetIntoSlotArguments[], opts: CanTokenBeEquippedWithAssetIntoSlotOptions): ReturnType<typeof useCanTokenBeEquippedWithAssetIntoSlot>;
    useChildIsInActive(args: ChildIsInActiveArguments[], opts: ChildIsInActiveOptions): ReturnType<typeof useChildIsInActive>;
    useChildOf(args: ChildOfArguments[], opts: ChildOfOptions): ReturnType<typeof useChildOf>;
    useChildrenOf(args: ChildrenOfArguments[], opts: ChildrenOfOptions): ReturnType<typeof useChildrenOf>;
    useCollectionMetadata(opts: CollectionMetadataOptions): ReturnType<typeof useCollectionMetadata>;
    useDirectOwnerOf(args: DirectOwnerOfArguments[], opts: DirectOwnerOfOptions): ReturnType<typeof useDirectOwnerOf>;
    useEquip(args: EquipArguments, opts: EquipOptions): ReturnType<typeof useEquip>;
    useGetActiveAssetPriorities(args: GetActiveAssetPrioritiesArguments[], opts: GetActiveAssetPrioritiesOptions): ReturnType<typeof useGetActiveAssetPriorities>;
    useGetActiveAssets(args: GetActiveAssetsArguments[], opts: GetActiveAssetsOptions): ReturnType<typeof useGetActiveAssets>;
    useGetApproved(args: GetApprovedArguments[], opts: GetApprovedOptions): ReturnType<typeof useGetApproved>;
    useGetApprovedForAssets(args: GetApprovedForAssetsArguments[], opts: GetApprovedForAssetsOptions): ReturnType<typeof useGetApprovedForAssets>;
    useGetAssetAndEquippableData(args: GetAssetAndEquippableDataArguments[], opts: GetAssetAndEquippableDataOptions): ReturnType<typeof useGetAssetAndEquippableData>;
    useGetAssetMetadata(args: GetAssetMetadataArguments[], opts: GetAssetMetadataOptions): ReturnType<typeof useGetAssetMetadata>;
    useGetAssetReplacements(args: GetAssetReplacementsArguments[], opts: GetAssetReplacementsOptions): ReturnType<typeof useGetAssetReplacements>;
    useGetEquipment(args: GetEquipmentArguments[], opts: GetEquipmentOptions): ReturnType<typeof useGetEquipment>;
    useGetLock(opts: GetLockOptions): ReturnType<typeof useGetLock>;
    useGetPendingAssets(args: GetPendingAssetsArguments[], opts: GetPendingAssetsOptions): ReturnType<typeof useGetPendingAssets>;
    useGetRoyaltyPercentage(opts: GetRoyaltyPercentageOptions): ReturnType<typeof useGetRoyaltyPercentage>;
    useGetRoyaltyRecipient(opts: GetRoyaltyRecipientOptions): ReturnType<typeof useGetRoyaltyRecipient>;
    useIsApprovedForAll(args: IsApprovedForAllArguments[], opts: IsApprovedForAllOptions): ReturnType<typeof useIsApprovedForAll>;
    useIsApprovedForAllForAssets(args: IsApprovedForAllForAssetsArguments[], opts: IsApprovedForAllForAssetsOptions): ReturnType<typeof useIsApprovedForAllForAssets>;
    useIsChildEquipped(args: IsChildEquippedArguments[], opts: IsChildEquippedOptions): ReturnType<typeof useIsChildEquipped>;
    useIsContributor(args: IsContributorArguments[], opts: IsContributorOptions): ReturnType<typeof useIsContributor>;
    useManageContributor(args: ManageContributorArguments, opts: ManageContributorOptions): ReturnType<typeof useManageContributor>;
    useMaxSupply(opts: MaxSupplyOptions): ReturnType<typeof useMaxSupply>;
    useMint(args: MintArguments, opts: MintOptions): ReturnType<typeof useMint>;
    useName(opts: NameOptions): ReturnType<typeof useName>;
    useNestMint(args: NestMintArguments, opts: NestMintOptions): ReturnType<typeof useNestMint>;
    useNestTransferFrom(args: NestTransferFromArguments, opts: NestTransferFromOptions): ReturnType<typeof useNestTransferFrom>;
    useOwner(opts: OwnerOptions): ReturnType<typeof useOwner>;
    useOwnerOf(args: OwnerOfArguments[], opts: OwnerOfOptions): ReturnType<typeof useOwnerOf>;
    usePendingChildOf(args: PendingChildOfArguments[], opts: PendingChildOfOptions): ReturnType<typeof usePendingChildOf>;
    usePendingChildrenOf(args: PendingChildrenOfArguments[], opts: PendingChildrenOfOptions): ReturnType<typeof usePendingChildrenOf>;
    usePricePerMint(opts: PricePerMintOptions): ReturnType<typeof usePricePerMint>;
    useRejectAllAssets(args: RejectAllAssetsArguments, opts: RejectAllAssetsOptions): ReturnType<typeof useRejectAllAssets>;
    useRejectAllChildren(args: RejectAllChildrenArguments, opts: RejectAllChildrenOptions): ReturnType<typeof useRejectAllChildren>;
    useRejectAsset(args: RejectAssetArguments, opts: RejectAssetOptions): ReturnType<typeof useRejectAsset>;
    useRenounceOwnership(opts: RenounceOwnershipOptions): ReturnType<typeof useRenounceOwnership>;
    useRoyaltyInfo(args: RoyaltyInfoArguments[], opts: RoyaltyInfoOptions): ReturnType<typeof useRoyaltyInfo>;
    useSafeTransferFrom(args: SafeTransferFromArguments, opts: SafeTransferFromOptions): ReturnType<typeof useSafeTransferFrom>;
    useSetApprovalForAll(args: SetApprovalForAllArguments, opts: SetApprovalForAllOptions): ReturnType<typeof useSetApprovalForAll>;
    useSetApprovalForAllForAssets(args: SetApprovalForAllForAssetsArguments, opts: SetApprovalForAllForAssetsOptions): ReturnType<typeof useSetApprovalForAllForAssets>;
    useSetLock(opts: SetLockOptions): ReturnType<typeof useSetLock>;
    useSetPriority(args: SetPriorityArguments, opts: SetPriorityOptions): ReturnType<typeof useSetPriority>;
    useSetValidParentForEquippableGroup(args: SetValidParentForEquippableGroupArguments, opts: SetValidParentForEquippableGroupOptions): ReturnType<typeof useSetValidParentForEquippableGroup>;
    useSupportsInterface(args: SupportsInterfaceArguments[], opts: SupportsInterfaceOptions): ReturnType<typeof useSupportsInterface>;
    useSymbol(opts: SymbolOptions): ReturnType<typeof useSymbol>;
    useTokenURI(args: TokenURIArguments[], opts: TokenURIOptions): ReturnType<typeof useTokenURI>;
    useTotalAssets(opts: TotalAssetsOptions): ReturnType<typeof useTotalAssets>;
    useTotalSupply(opts: TotalSupplyOptions): ReturnType<typeof useTotalSupply>;
    useTransferChild(args: TransferChildArguments, opts: TransferChildOptions): ReturnType<typeof useTransferChild>;
    useTransferFrom(args: TransferFromArguments, opts: TransferFromOptions): ReturnType<typeof useTransferFrom>;
    useTransferOwnership(args: TransferOwnershipArguments, opts: TransferOwnershipOptions): ReturnType<typeof useTransferOwnership>;
    useUnequip(args: UnequipArguments, opts: UnequipOptions): ReturnType<typeof useUnequip>;
    useUpdateRoyaltyRecipient(args: UpdateRoyaltyRecipientArguments, opts: UpdateRoyaltyRecipientOptions): ReturnType<typeof useUpdateRoyaltyRecipient>;
    useWithdrawRaised(args: WithdrawRaisedArguments, opts: WithdrawRaisedOptions): ReturnType<typeof useWithdrawRaised>;
};
